version: '2.1'
orbs:
  node: circleci/node@5.2.0
  ruby: circleci/ruby@2.1.1
  codecov: codecov/codecov@4.0.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:3.2.2-node
      - environment:
          POSTGRES_DB: dough_fin_be_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: dough_fin
        image: circleci/postgres:9.5-alpine
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: dough_fin
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for DB
      - run:
          command: bundle exec rails db:schema:load --trace
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
      - run:
          name: show results
          command: |
            ls -la /tmp/test-results/rspec/
#      - store_test_results:
#          path: /tmp/test-results/rspec/
      - persist_to_workspace:
          root: /tmp
          paths:
            - test-results/rspec
  upload_cov:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - ruby/install-deps
      - attach_workspace:
          at: /tmp
      - run:
          name: show results
          command: |
            ls -la
      - codecov/upload:
          file: /tmp/test-results/rspec/results.xml
          cli_args: -v
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload_cov:
          requires:
            - test

