version: '2.1'
orbs:
  node: circleci/node@5.2.0
  ruby: circleci/ruby@2.1.1
  codecov: codecov/codecov@4.0.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - checkout
      - ruby/install-deps
#      - run: mkdir -p tmp/test-results/rspec
#      - run: echo 'hello world' > tmp/test-results/rspec/results.xml
#      - run: ls -alh tmp/test-results/rspec
#      - persist_to_workspace:
#          root: tmp
#          paths: test-results/rspec
  access_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run: pwd
      - run: ls -alh /tmp
      - run: ls -alh /tmp/test-results
      - run: ls -alh /tmp/test-results/rspec
      - run: |
          if [[ `cat /tmp/test-results/rspec/results.xml` == "hello world" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  test:
    docker:
      - image: cimg/ruby:3.2.2-node
      - environment:
          POSTGRES_DB: dough_fin_be_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: dough_fin
        image: circleci/postgres:9.5-alpine
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: dough_fin
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for DB
      - run:
          command: bundle exec rails db:schema:load --trace
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
      - run:
          name: show results
          command: |
            ls -la /tmp/test-results/rspec/
            cat /tmp/test-results/rspec/results.xml
      - persist_to_workspace:
          root: /tmp
          paths:
            - test-results/rspec
  automated-api-tests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Postman CLI
          command: |
            curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - run:
          name: Login using your API key
          command: postman login --with-api-key $POSTMAN_API_KEY
      - run: |
          postman collection run "32691430-d6ebc16a-355e-4d35-bb2c-fd77c006e18c" -e "31402405-b0690f20-1d59-4edc-9f1d-e8c46bf9afe8"
  upload_cov:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - checkout
      - ruby/install-deps
      - attach_workspace:
          at: /tmp
#      - run: ls -alh /tmp
#      - run: ls -alh /tmp/test-results
#      - run: ls -alh /tmp/test-results/rspec
      - run: cat /tmp/test-results/rspec/results.xml
      - codecov/upload:
          file: /tmp/test-results/rspec/results.xml
          cli_args: -v
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload_cov:
          requires:
            - test
#      - automated_api_tests:
#          requires:
#            - build
#      - access_file:
#          requires:
#            - build

